// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatalogClient creates a new instance of MockCatalogClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogClient {
	mock := &MockCatalogClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogClient is an autogenerated mock type for the CatalogClient type
type MockCatalogClient struct {
	mock.Mock
}

type MockCatalogClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogClient) EXPECT() *MockCatalogClient_Expecter {
	return &MockCatalogClient_Expecter{mock: &_m.Mock}
}

// AddArtifact provides a mock function for the type MockCatalogClient
func (_mock *MockCatalogClient) AddArtifact(context1 context.Context, s string, s1 string, addArtifactRequest client.AddArtifactRequest) (client.Artifact, error) {
	ret := _mock.Called(context1, s, s1, addArtifactRequest)

	if len(ret) == 0 {
		panic("no return value specified for AddArtifact")
	}

	var r0 client.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AddArtifactRequest) (client.Artifact, error)); ok {
		return returnFunc(context1, s, s1, addArtifactRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AddArtifactRequest) client.Artifact); ok {
		r0 = returnFunc(context1, s, s1, addArtifactRequest)
	} else {
		r0 = ret.Get(0).(client.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.AddArtifactRequest) error); ok {
		r1 = returnFunc(context1, s, s1, addArtifactRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogClient_AddArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddArtifact'
type MockCatalogClient_AddArtifact_Call struct {
	*mock.Call
}

// AddArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - addArtifactRequest client.AddArtifactRequest
func (_e *MockCatalogClient_Expecter) AddArtifact(context1 interface{}, s interface{}, s1 interface{}, addArtifactRequest interface{}) *MockCatalogClient_AddArtifact_Call {
	return &MockCatalogClient_AddArtifact_Call{Call: _e.mock.On("AddArtifact", context1, s, s1, addArtifactRequest)}
}

func (_c *MockCatalogClient_AddArtifact_Call) Run(run func(context1 context.Context, s string, s1 string, addArtifactRequest client.AddArtifactRequest)) *MockCatalogClient_AddArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.AddArtifactRequest
		if args[3] != nil {
			arg3 = args[3].(client.AddArtifactRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCatalogClient_AddArtifact_Call) Return(artifact client.Artifact, err error) *MockCatalogClient_AddArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockCatalogClient_AddArtifact_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, addArtifactRequest client.AddArtifactRequest) (client.Artifact, error)) *MockCatalogClient_AddArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDraftVersion provides a mock function for the type MockCatalogClient
func (_mock *MockCatalogClient) CreateDraftVersion(context1 context.Context, s string, createDraftVersionRequest client.CreateDraftVersionRequest) (client.ImageVersion, error) {
	ret := _mock.Called(context1, s, createDraftVersionRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraftVersion")
	}

	var r0 client.ImageVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CreateDraftVersionRequest) (client.ImageVersion, error)); ok {
		return returnFunc(context1, s, createDraftVersionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CreateDraftVersionRequest) client.ImageVersion); ok {
		r0 = returnFunc(context1, s, createDraftVersionRequest)
	} else {
		r0 = ret.Get(0).(client.ImageVersion)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.CreateDraftVersionRequest) error); ok {
		r1 = returnFunc(context1, s, createDraftVersionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogClient_CreateDraftVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDraftVersion'
type MockCatalogClient_CreateDraftVersion_Call struct {
	*mock.Call
}

// CreateDraftVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - createDraftVersionRequest client.CreateDraftVersionRequest
func (_e *MockCatalogClient_Expecter) CreateDraftVersion(context1 interface{}, s interface{}, createDraftVersionRequest interface{}) *MockCatalogClient_CreateDraftVersion_Call {
	return &MockCatalogClient_CreateDraftVersion_Call{Call: _e.mock.On("CreateDraftVersion", context1, s, createDraftVersionRequest)}
}

func (_c *MockCatalogClient_CreateDraftVersion_Call) Run(run func(context1 context.Context, s string, createDraftVersionRequest client.CreateDraftVersionRequest)) *MockCatalogClient_CreateDraftVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.CreateDraftVersionRequest
		if args[2] != nil {
			arg2 = args[2].(client.CreateDraftVersionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatalogClient_CreateDraftVersion_Call) Return(imageVersion client.ImageVersion, err error) *MockCatalogClient_CreateDraftVersion_Call {
	_c.Call.Return(imageVersion, err)
	return _c
}

func (_c *MockCatalogClient_CreateDraftVersion_Call) RunAndReturn(run func(context1 context.Context, s string, createDraftVersionRequest client.CreateDraftVersionRequest) (client.ImageVersion, error)) *MockCatalogClient_CreateDraftVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImage provides a mock function for the type MockCatalogClient
func (_mock *MockCatalogClient) CreateImage(context1 context.Context, createImageRequest client.CreateImageRequest) (client.Image, error) {
	ret := _mock.Called(context1, createImageRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateImage")
	}

	var r0 client.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.CreateImageRequest) (client.Image, error)); ok {
		return returnFunc(context1, createImageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.CreateImageRequest) client.Image); ok {
		r0 = returnFunc(context1, createImageRequest)
	} else {
		r0 = ret.Get(0).(client.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.CreateImageRequest) error); ok {
		r1 = returnFunc(context1, createImageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogClient_CreateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImage'
type MockCatalogClient_CreateImage_Call struct {
	*mock.Call
}

// CreateImage is a helper method to define mock.On call
//   - context1 context.Context
//   - createImageRequest client.CreateImageRequest
func (_e *MockCatalogClient_Expecter) CreateImage(context1 interface{}, createImageRequest interface{}) *MockCatalogClient_CreateImage_Call {
	return &MockCatalogClient_CreateImage_Call{Call: _e.mock.On("CreateImage", context1, createImageRequest)}
}

func (_c *MockCatalogClient_CreateImage_Call) Run(run func(context1 context.Context, createImageRequest client.CreateImageRequest)) *MockCatalogClient_CreateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.CreateImageRequest
		if args[1] != nil {
			arg1 = args[1].(client.CreateImageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogClient_CreateImage_Call) Return(image client.Image, err error) *MockCatalogClient_CreateImage_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockCatalogClient_CreateImage_Call) RunAndReturn(run func(context1 context.Context, createImageRequest client.CreateImageRequest) (client.Image, error)) *MockCatalogClient_CreateImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteArtifact provides a mock function for the type MockCatalogClient
func (_mock *MockCatalogClient) DeleteArtifact(context1 context.Context, s string, s1 string, s2 string) error {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogClient_DeleteArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtifact'
type MockCatalogClient_DeleteArtifact_Call struct {
	*mock.Call
}

// DeleteArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockCatalogClient_Expecter) DeleteArtifact(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}) *MockCatalogClient_DeleteArtifact_Call {
	return &MockCatalogClient_DeleteArtifact_Call{Call: _e.mock.On("DeleteArtifact", context1, s, s1, s2)}
}

func (_c *MockCatalogClient_DeleteArtifact_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockCatalogClient_DeleteArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCatalogClient_DeleteArtifact_Call) Return(err error) *MockCatalogClient_DeleteArtifact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogClient_DeleteArtifact_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) error) *MockCatalogClient_DeleteArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishJob provides a mock function for the type MockCatalogClient
func (_mock *MockCatalogClient) GetPublishJob(context1 context.Context, s string) (client.PublishJob, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishJob")
	}

	var r0 client.PublishJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.PublishJob, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.PublishJob); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(client.PublishJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogClient_GetPublishJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishJob'
type MockCatalogClient_GetPublishJob_Call struct {
	*mock.Call
}

// GetPublishJob is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockCatalogClient_Expecter) GetPublishJob(context1 interface{}, s interface{}) *MockCatalogClient_GetPublishJob_Call {
	return &MockCatalogClient_GetPublishJob_Call{Call: _e.mock.On("GetPublishJob", context1, s)}
}

func (_c *MockCatalogClient_GetPublishJob_Call) Run(run func(context1 context.Context, s string)) *MockCatalogClient_GetPublishJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogClient_GetPublishJob_Call) Return(publishJob client.PublishJob, err error) *MockCatalogClient_GetPublishJob_Call {
	_c.Call.Return(publishJob, err)
	return _c
}

func (_c *MockCatalogClient_GetPublishJob_Call) RunAndReturn(run func(context1 context.Context, s string) (client.PublishJob, error)) *MockCatalogClient_GetPublishJob_Call {
	_c.Call.Return(run)
	return _c
}

// PublishVersion provides a mock function for the type MockCatalogClient
func (_mock *MockCatalogClient) PublishVersion(context1 context.Context, s string, s1 string) (client.PublishJob, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for PublishVersion")
	}

	var r0 client.PublishJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (client.PublishJob, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) client.PublishJob); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(client.PublishJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogClient_PublishVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishVersion'
type MockCatalogClient_PublishVersion_Call struct {
	*mock.Call
}

// PublishVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockCatalogClient_Expecter) PublishVersion(context1 interface{}, s interface{}, s1 interface{}) *MockCatalogClient_PublishVersion_Call {
	return &MockCatalogClient_PublishVersion_Call{Call: _e.mock.On("PublishVersion", context1, s, s1)}
}

func (_c *MockCatalogClient_PublishVersion_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockCatalogClient_PublishVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatalogClient_PublishVersion_Call) Return(publishJob client.PublishJob, err error) *MockCatalogClient_PublishVersion_Call {
	_c.Call.Return(publishJob, err)
	return _c
}

func (_c *MockCatalogClient_PublishVersion_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (client.PublishJob, error)) *MockCatalogClient_PublishVersion_Call {
	_c.Call.Return(run)
	return _c
}

// PutAlias provides a mock function for the type MockCatalogClient
func (_mock *MockCatalogClient) PutAlias(context1 context.Context, s string, s1 string, putAliasRequest client.PutAliasRequest) (client.Alias, error) {
	ret := _mock.Called(context1, s, s1, putAliasRequest)

	if len(ret) == 0 {
		panic("no return value specified for PutAlias")
	}

	var r0 client.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.PutAliasRequest) (client.Alias, error)); ok {
		return returnFunc(context1, s, s1, putAliasRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.PutAliasRequest) client.Alias); ok {
		r0 = returnFunc(context1, s, s1, putAliasRequest)
	} else {
		r0 = ret.Get(0).(client.Alias)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.PutAliasRequest) error); ok {
		r1 = returnFunc(context1, s, s1, putAliasRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogClient_PutAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutAlias'
type MockCatalogClient_PutAlias_Call struct {
	*mock.Call
}

// PutAlias is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - putAliasRequest client.PutAliasRequest
func (_e *MockCatalogClient_Expecter) PutAlias(context1 interface{}, s interface{}, s1 interface{}, putAliasRequest interface{}) *MockCatalogClient_PutAlias_Call {
	return &MockCatalogClient_PutAlias_Call{Call: _e.mock.On("PutAlias", context1, s, s1, putAliasRequest)}
}

func (_c *MockCatalogClient_PutAlias_Call) Run(run func(context1 context.Context, s string, s1 string, putAliasRequest client.PutAliasRequest)) *MockCatalogClient_PutAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.PutAliasRequest
		if args[3] != nil {
			arg3 = args[3].(client.PutAliasRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCatalogClient_PutAlias_Call) Return(alias client.Alias, err error) *MockCatalogClient_PutAlias_Call {
	_c.Call.Return(alias, err)
	return _c
}

func (_c *MockCatalogClient_PutAlias_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, putAliasRequest client.PutAliasRequest) (client.Alias, error)) *MockCatalogClient_PutAlias_Call {
	_c.Call.Return(run)
	return _c
}
