// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/meigma/imgsrv/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUploadsClient creates a new instance of MockUploadsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadsClient {
	mock := &MockUploadsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadsClient is an autogenerated mock type for the UploadsClient type
type MockUploadsClient struct {
	mock.Mock
}

type MockUploadsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadsClient) EXPECT() *MockUploadsClient_Expecter {
	return &MockUploadsClient_Expecter{mock: &_m.Mock}
}

// AbortUpload provides a mock function for the type MockUploadsClient
func (_mock *MockUploadsClient) AbortUpload(context1 context.Context, s string) (client.UploadSession, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for AbortUpload")
	}

	var r0 client.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.UploadSession, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.UploadSession); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(client.UploadSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadsClient_AbortUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortUpload'
type MockUploadsClient_AbortUpload_Call struct {
	*mock.Call
}

// AbortUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUploadsClient_Expecter) AbortUpload(context1 interface{}, s interface{}) *MockUploadsClient_AbortUpload_Call {
	return &MockUploadsClient_AbortUpload_Call{Call: _e.mock.On("AbortUpload", context1, s)}
}

func (_c *MockUploadsClient_AbortUpload_Call) Run(run func(context1 context.Context, s string)) *MockUploadsClient_AbortUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadsClient_AbortUpload_Call) Return(uploadSession client.UploadSession, err error) *MockUploadsClient_AbortUpload_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *MockUploadsClient_AbortUpload_Call) RunAndReturn(run func(context1 context.Context, s string) (client.UploadSession, error)) *MockUploadsClient_AbortUpload_Call {
	_c.Call.Return(run)
	return _c
}

// BeginUpload provides a mock function for the type MockUploadsClient
func (_mock *MockUploadsClient) BeginUpload(context1 context.Context, beginUploadRequest client.BeginUploadRequest) (client.UploadSession, error) {
	ret := _mock.Called(context1, beginUploadRequest)

	if len(ret) == 0 {
		panic("no return value specified for BeginUpload")
	}

	var r0 client.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.BeginUploadRequest) (client.UploadSession, error)); ok {
		return returnFunc(context1, beginUploadRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.BeginUploadRequest) client.UploadSession); ok {
		r0 = returnFunc(context1, beginUploadRequest)
	} else {
		r0 = ret.Get(0).(client.UploadSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.BeginUploadRequest) error); ok {
		r1 = returnFunc(context1, beginUploadRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadsClient_BeginUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginUpload'
type MockUploadsClient_BeginUpload_Call struct {
	*mock.Call
}

// BeginUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - beginUploadRequest client.BeginUploadRequest
func (_e *MockUploadsClient_Expecter) BeginUpload(context1 interface{}, beginUploadRequest interface{}) *MockUploadsClient_BeginUpload_Call {
	return &MockUploadsClient_BeginUpload_Call{Call: _e.mock.On("BeginUpload", context1, beginUploadRequest)}
}

func (_c *MockUploadsClient_BeginUpload_Call) Run(run func(context1 context.Context, beginUploadRequest client.BeginUploadRequest)) *MockUploadsClient_BeginUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.BeginUploadRequest
		if args[1] != nil {
			arg1 = args[1].(client.BeginUploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadsClient_BeginUpload_Call) Return(uploadSession client.UploadSession, err error) *MockUploadsClient_BeginUpload_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *MockUploadsClient_BeginUpload_Call) RunAndReturn(run func(context1 context.Context, beginUploadRequest client.BeginUploadRequest) (client.UploadSession, error)) *MockUploadsClient_BeginUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteUpload provides a mock function for the type MockUploadsClient
func (_mock *MockUploadsClient) CompleteUpload(context1 context.Context, s string, completeUploadRequest client.CompleteUploadRequest) (client.UploadSession, error) {
	ret := _mock.Called(context1, s, completeUploadRequest)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 client.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CompleteUploadRequest) (client.UploadSession, error)); ok {
		return returnFunc(context1, s, completeUploadRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CompleteUploadRequest) client.UploadSession); ok {
		r0 = returnFunc(context1, s, completeUploadRequest)
	} else {
		r0 = ret.Get(0).(client.UploadSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.CompleteUploadRequest) error); ok {
		r1 = returnFunc(context1, s, completeUploadRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadsClient_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type MockUploadsClient_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - completeUploadRequest client.CompleteUploadRequest
func (_e *MockUploadsClient_Expecter) CompleteUpload(context1 interface{}, s interface{}, completeUploadRequest interface{}) *MockUploadsClient_CompleteUpload_Call {
	return &MockUploadsClient_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", context1, s, completeUploadRequest)}
}

func (_c *MockUploadsClient_CompleteUpload_Call) Run(run func(context1 context.Context, s string, completeUploadRequest client.CompleteUploadRequest)) *MockUploadsClient_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.CompleteUploadRequest
		if args[2] != nil {
			arg2 = args[2].(client.CompleteUploadRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadsClient_CompleteUpload_Call) Return(uploadSession client.UploadSession, err error) *MockUploadsClient_CompleteUpload_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *MockUploadsClient_CompleteUpload_Call) RunAndReturn(run func(context1 context.Context, s string, completeUploadRequest client.CompleteUploadRequest) (client.UploadSession, error)) *MockUploadsClient_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpload provides a mock function for the type MockUploadsClient
func (_mock *MockUploadsClient) GetUpload(context1 context.Context, s string) (client.UploadSession, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetUpload")
	}

	var r0 client.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.UploadSession, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.UploadSession); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(client.UploadSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadsClient_GetUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpload'
type MockUploadsClient_GetUpload_Call struct {
	*mock.Call
}

// GetUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUploadsClient_Expecter) GetUpload(context1 interface{}, s interface{}) *MockUploadsClient_GetUpload_Call {
	return &MockUploadsClient_GetUpload_Call{Call: _e.mock.On("GetUpload", context1, s)}
}

func (_c *MockUploadsClient_GetUpload_Call) Run(run func(context1 context.Context, s string)) *MockUploadsClient_GetUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadsClient_GetUpload_Call) Return(uploadSession client.UploadSession, err error) *MockUploadsClient_GetUpload_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *MockUploadsClient_GetUpload_Call) RunAndReturn(run func(context1 context.Context, s string) (client.UploadSession, error)) *MockUploadsClient_GetUpload_Call {
	_c.Call.Return(run)
	return _c
}

// PutUploadPart provides a mock function for the type MockUploadsClient
func (_mock *MockUploadsClient) PutUploadPart(context1 context.Context, s string, n int, reader io.Reader, n1 int64) (client.UploadPart, error) {
	ret := _mock.Called(context1, s, n, reader, n1)

	if len(ret) == 0 {
		panic("no return value specified for PutUploadPart")
	}

	var r0 client.UploadPart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, io.Reader, int64) (client.UploadPart, error)); ok {
		return returnFunc(context1, s, n, reader, n1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, io.Reader, int64) client.UploadPart); ok {
		r0 = returnFunc(context1, s, n, reader, n1)
	} else {
		r0 = ret.Get(0).(client.UploadPart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, io.Reader, int64) error); ok {
		r1 = returnFunc(context1, s, n, reader, n1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadsClient_PutUploadPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutUploadPart'
type MockUploadsClient_PutUploadPart_Call struct {
	*mock.Call
}

// PutUploadPart is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - n int
//   - reader io.Reader
//   - n1 int64
func (_e *MockUploadsClient_Expecter) PutUploadPart(context1 interface{}, s interface{}, n interface{}, reader interface{}, n1 interface{}) *MockUploadsClient_PutUploadPart_Call {
	return &MockUploadsClient_PutUploadPart_Call{Call: _e.mock.On("PutUploadPart", context1, s, n, reader, n1)}
}

func (_c *MockUploadsClient_PutUploadPart_Call) Run(run func(context1 context.Context, s string, n int, reader io.Reader, n1 int64)) *MockUploadsClient_PutUploadPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUploadsClient_PutUploadPart_Call) Return(uploadPart client.UploadPart, err error) *MockUploadsClient_PutUploadPart_Call {
	_c.Call.Return(uploadPart, err)
	return _c
}

func (_c *MockUploadsClient_PutUploadPart_Call) RunAndReturn(run func(context1 context.Context, s string, n int, reader io.Reader, n1 int64) (client.UploadPart, error)) *MockUploadsClient_PutUploadPart_Call {
	_c.Call.Return(run)
	return _c
}
