// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package incusos

import (
	"github.com/meigma/imgcli/schemas/core"
)

type Variant struct {
	Artifact core.ArtifactIntent `json:"artifact"`
}

type Config struct {
	Defaults any/* CUE top */ `json:"defaults,omitempty"`

	Variants map[core.VariantName]Variant `json:"variants"`
}
