// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package core

type Name string

type VariantName string

type ArtifactKey string

type Architecture string

type ArtifactFormat string

type ProviderName string

type Image struct {
	Name Name `json:"name"`

	Description string `json:"description,omitempty"`

	Labels map[string]string `json:"labels,omitempty"`

	Annotations map[string]string `json:"annotations,omitempty"`
}

type OutputDefaults struct {
	// Defaults to ./dist unless overridden by CLI flag or config.
	Dir string `json:"dir,omitempty"`
}

type PublishIntent struct {
	// Optional override if imgsrv image identity should differ from image.name.
	ImageName Name `json:"imageName,omitempty"`

	Labels map[string]string `json:"labels,omitempty"`

	Annotations map[string]string `json:"annotations,omitempty"`
}

type ArtifactIntent struct {
	Variant VariantName `json:"variant"`

	Provider ProviderName `json:"provider"`

	Os string `json:"os"`

	Architecture Architecture `json:"architecture"`

	Format ArtifactFormat `json:"format"`

	MediaType string `json:"mediaType,omitempty"`

	Filename string `json:"filename,omitempty"`

	Labels map[string]string `json:"labels,omitempty"`

	Annotations map[string]string `json:"annotations,omitempty"`
}

type ResolvedArtifact struct {
	ArtifactKey ArtifactKey `json:"artifactKey"`

	ImageName string `json:"imageName"`

	Version string `json:"version,omitempty"`

	Variant VariantName `json:"variant"`

	Provider ProviderName `json:"provider"`

	Os string `json:"os"`

	Architecture Architecture `json:"architecture"`

	Format ArtifactFormat `json:"format"`

	MediaType string `json:"mediaType"`

	Path string `json:"path"`

	Labels map[string]string `json:"labels,omitempty"`

	Annotations map[string]string `json:"annotations,omitempty"`

	// Populated after build.
	Digest string `json:"digest,omitempty"`

	Size int64 `json:"size,omitempty"`
}

type ResolvedPlan struct {
	Image Image `json:"image"`

	// Supplied by CLI or release environment. Not required in the config file.
	Version string `json:"version,omitempty"`

	OutputDir string `json:"outputDir"`

	Artifacts map[ArtifactKey]ResolvedArtifact `json:"artifacts"`
}
