// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgcli/internal/cache"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockService
func (_mock *MockService) Fetch(ctx context.Context, req cache.FetchRequest) (cache.Blob, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 cache.Blob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cache.FetchRequest) (cache.Blob, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cache.FetchRequest) cache.Blob); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(cache.Blob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cache.FetchRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - req cache.FetchRequest
func (_e *MockService_Expecter) Fetch(ctx interface{}, req interface{}) *MockService_Fetch_Call {
	return &MockService_Fetch_Call{Call: _e.mock.On("Fetch", ctx, req)}
}

func (_c *MockService_Fetch_Call) Run(run func(ctx context.Context, req cache.FetchRequest)) *MockService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cache.FetchRequest
		if args[1] != nil {
			arg1 = args[1].(cache.FetchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Fetch_Call) Return(blob cache.Blob, err error) *MockService_Fetch_Call {
	_c.Call.Return(blob, err)
	return _c
}

func (_c *MockService_Fetch_Call) RunAndReturn(run func(ctx context.Context, req cache.FetchRequest) (cache.Blob, error)) *MockService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
