// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package schemas

import (
	"github.com/meigma/imgcli/schemas/core"
	incusosprovider "github.com/meigma/imgcli/schemas/providers/incusos"
)

type Config struct {
	ApiVersion string `json:"apiVersion"`

	Kind string `json:"kind"`

	Image core.Image `json:"image"`

	Output *core.OutputDefaults `json:"output,omitempty"`

	Publish *core.PublishIntent `json:"publish,omitempty"`

	Incusos *incusosprovider.Config `json:"incusos,omitempty"`
}

type Image core.Image

type OutputDefaults core.OutputDefaults

type PublishIntent core.PublishIntent

type ArtifactIntent core.ArtifactIntent

type ArtifactMetadata struct {
	ApiVersion string `json:"apiVersion"`

	Kind string `json:"kind"`

	Artifact core.ResolvedArtifact `json:"artifact"`
}

type ResolvedArtifact core.ResolvedArtifact

type ResolvedPlan core.ResolvedPlan

type Name core.Name

type VariantName core.VariantName

type ArtifactKey core.ArtifactKey

type Architecture core.Architecture

type ArtifactFormat core.ArtifactFormat
